/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TrackRouteImport } from './routes/track'
import { Route as ConsoleConsoleRouteImport } from './routes/_console/_console'
import { Route as ConsoleConsoleActivityRouteImport } from './routes/_console/_console.activity'
import { Route as ConsoleConsoleAtRiskRouteImport } from './routes/_console/_console.at-risk'
import { Route as ConsoleConsoleDashboardRouteImport } from './routes/_console/_console.dashboard'
import { Route as ConsoleConsoleDriversRouteImport } from './routes/_console/_console/drivers'
import { Route as ConsoleConsoleMerchantsRouteImport } from './routes/_console/_console.merchants'
import { Route as ConsoleConsoleConsoleDeliveryCompaniesRouteImport } from './routes/_console/_console/_console.delivery-companies'
import { Route as ConsoleConsoleShipmentsIndexRouteImport } from './routes/_console/_console.shipments.index'
import { Route as ConsoleConsoleShipmentsShipmentIdRouteImport } from './routes/_console/_console.shipments.$shipmentId'
import { Route as ConsoleConsoleShipmentsNewRouteImport } from './routes/_console/_console.shipments.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleConsoleRoute = ConsoleConsoleRouteImport.update({
  id: '/_console/_console',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleConsoleActivityRoute = ConsoleConsoleActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => ConsoleConsoleRoute,
} as any)
const ConsoleConsoleAtRiskRoute = ConsoleConsoleAtRiskRouteImport.update({
  id: '/at-risk',
  path: '/at-risk',
  getParentRoute: () => ConsoleConsoleRoute,
} as any)
const ConsoleConsoleDashboardRoute = ConsoleConsoleDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ConsoleConsoleRoute,
} as any)
const ConsoleConsoleDriversRoute = ConsoleConsoleDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => ConsoleConsoleRoute,
} as any)
const ConsoleConsoleMerchantsRoute = ConsoleConsoleMerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => ConsoleConsoleRoute,
} as any)
const ConsoleConsoleConsoleDeliveryCompaniesRoute =
  ConsoleConsoleConsoleDeliveryCompaniesRouteImport.update({
    id: '/_console/delivery-companies',
    path: '/delivery-companies',
    getParentRoute: () => ConsoleConsoleRoute,
  } as any)
const ConsoleConsoleShipmentsIndexRoute =
  ConsoleConsoleShipmentsIndexRouteImport.update({
    id: '/shipments/',
    path: '/shipments/',
    getParentRoute: () => ConsoleConsoleRoute,
  } as any)
const ConsoleConsoleShipmentsShipmentIdRoute =
  ConsoleConsoleShipmentsShipmentIdRouteImport.update({
    id: '/shipments/$shipmentId',
    path: '/shipments/$shipmentId',
    getParentRoute: () => ConsoleConsoleRoute,
  } as any)
const ConsoleConsoleShipmentsNewRoute =
  ConsoleConsoleShipmentsNewRouteImport.update({
    id: '/shipments/new',
    path: '/shipments/new',
    getParentRoute: () => ConsoleConsoleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/track': typeof TrackRoute
  '/activity': typeof ConsoleConsoleActivityRoute
  '/at-risk': typeof ConsoleConsoleAtRiskRoute
  '/dashboard': typeof ConsoleConsoleDashboardRoute
  '/drivers': typeof ConsoleConsoleDriversRoute
  '/merchants': typeof ConsoleConsoleMerchantsRoute
  '/delivery-companies': typeof ConsoleConsoleConsoleDeliveryCompaniesRoute
  '/shipments/$shipmentId': typeof ConsoleConsoleShipmentsShipmentIdRoute
  '/shipments/new': typeof ConsoleConsoleShipmentsNewRoute
  '/shipments/': typeof ConsoleConsoleShipmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/track': typeof TrackRoute
  '/activity': typeof ConsoleConsoleActivityRoute
  '/at-risk': typeof ConsoleConsoleAtRiskRoute
  '/dashboard': typeof ConsoleConsoleDashboardRoute
  '/drivers': typeof ConsoleConsoleDriversRoute
  '/merchants': typeof ConsoleConsoleMerchantsRoute
  '/delivery-companies': typeof ConsoleConsoleConsoleDeliveryCompaniesRoute
  '/shipments/$shipmentId': typeof ConsoleConsoleShipmentsShipmentIdRoute
  '/shipments/new': typeof ConsoleConsoleShipmentsNewRoute
  '/shipments': typeof ConsoleConsoleShipmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/track': typeof TrackRoute
  '/_console/_console': typeof ConsoleConsoleRouteWithChildren
  '/_console/_console/activity': typeof ConsoleConsoleActivityRoute
  '/_console/_console/at-risk': typeof ConsoleConsoleAtRiskRoute
  '/_console/_console/dashboard': typeof ConsoleConsoleDashboardRoute
  '/_console/_console/drivers': typeof ConsoleConsoleDriversRoute
  '/_console/_console/merchants': typeof ConsoleConsoleMerchantsRoute
  '/_console/_console/_console/delivery-companies': typeof ConsoleConsoleConsoleDeliveryCompaniesRoute
  '/_console/_console/shipments/$shipmentId': typeof ConsoleConsoleShipmentsShipmentIdRoute
  '/_console/_console/shipments/new': typeof ConsoleConsoleShipmentsNewRoute
  '/_console/_console/shipments/': typeof ConsoleConsoleShipmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/track'
    | '/activity'
    | '/at-risk'
    | '/dashboard'
    | '/drivers'
    | '/merchants'
    | '/delivery-companies'
    | '/shipments/$shipmentId'
    | '/shipments/new'
    | '/shipments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/track'
    | '/activity'
    | '/at-risk'
    | '/dashboard'
    | '/drivers'
    | '/merchants'
    | '/delivery-companies'
    | '/shipments/$shipmentId'
    | '/shipments/new'
    | '/shipments'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/track'
    | '/_console/_console'
    | '/_console/_console/activity'
    | '/_console/_console/at-risk'
    | '/_console/_console/dashboard'
    | '/_console/_console/drivers'
    | '/_console/_console/merchants'
    | '/_console/_console/_console/delivery-companies'
    | '/_console/_console/shipments/$shipmentId'
    | '/_console/_console/shipments/new'
    | '/_console/_console/shipments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  TrackRoute: typeof TrackRoute
  ConsoleConsoleRoute: typeof ConsoleConsoleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/_console': {
      id: '/_console/_console'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsoleConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/_console/activity': {
      id: '/_console/_console/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ConsoleConsoleActivityRouteImport
      parentRoute: typeof ConsoleConsoleRoute
    }
    '/_console/_console/at-risk': {
      id: '/_console/_console/at-risk'
      path: '/at-risk'
      fullPath: '/at-risk'
      preLoaderRoute: typeof ConsoleConsoleAtRiskRouteImport
      parentRoute: typeof ConsoleConsoleRoute
    }
    '/_console/_console/dashboard': {
      id: '/_console/_console/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ConsoleConsoleDashboardRouteImport
      parentRoute: typeof ConsoleConsoleRoute
    }
    '/_console/_console/drivers': {
      id: '/_console/_console/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof ConsoleConsoleDriversRouteImport
      parentRoute: typeof ConsoleConsoleRoute
    }
    '/_console/_console/merchants': {
      id: '/_console/_console/merchants'
      path: '/merchants'
      fullPath: '/merchants'
      preLoaderRoute: typeof ConsoleConsoleMerchantsRouteImport
      parentRoute: typeof ConsoleConsoleRoute
    }
    '/_console/_console/_console/delivery-companies': {
      id: '/_console/_console/_console/delivery-companies'
      path: '/delivery-companies'
      fullPath: '/delivery-companies'
      preLoaderRoute: typeof ConsoleConsoleConsoleDeliveryCompaniesRouteImport
      parentRoute: typeof ConsoleConsoleRoute
    }
    '/_console/_console/shipments/': {
      id: '/_console/_console/shipments/'
      path: '/shipments'
      fullPath: '/shipments/'
      preLoaderRoute: typeof ConsoleConsoleShipmentsIndexRouteImport
      parentRoute: typeof ConsoleConsoleRoute
    }
    '/_console/_console/shipments/$shipmentId': {
      id: '/_console/_console/shipments/$shipmentId'
      path: '/shipments/$shipmentId'
      fullPath: '/shipments/$shipmentId'
      preLoaderRoute: typeof ConsoleConsoleShipmentsShipmentIdRouteImport
      parentRoute: typeof ConsoleConsoleRoute
    }
    '/_console/_console/shipments/new': {
      id: '/_console/_console/shipments/new'
      path: '/shipments/new'
      fullPath: '/shipments/new'
      preLoaderRoute: typeof ConsoleConsoleShipmentsNewRouteImport
      parentRoute: typeof ConsoleConsoleRoute
    }
  }
}

interface ConsoleConsoleRouteChildren {
  ConsoleConsoleActivityRoute: typeof ConsoleConsoleActivityRoute
  ConsoleConsoleAtRiskRoute: typeof ConsoleConsoleAtRiskRoute
  ConsoleConsoleDashboardRoute: typeof ConsoleConsoleDashboardRoute
  ConsoleConsoleDriversRoute: typeof ConsoleConsoleDriversRoute
  ConsoleConsoleMerchantsRoute: typeof ConsoleConsoleMerchantsRoute
  ConsoleConsoleConsoleDeliveryCompaniesRoute: typeof ConsoleConsoleConsoleDeliveryCompaniesRoute
  ConsoleConsoleShipmentsShipmentIdRoute: typeof ConsoleConsoleShipmentsShipmentIdRoute
  ConsoleConsoleShipmentsNewRoute: typeof ConsoleConsoleShipmentsNewRoute
  ConsoleConsoleShipmentsIndexRoute: typeof ConsoleConsoleShipmentsIndexRoute
}

const ConsoleConsoleRouteChildren: ConsoleConsoleRouteChildren = {
  ConsoleConsoleActivityRoute: ConsoleConsoleActivityRoute,
  ConsoleConsoleAtRiskRoute: ConsoleConsoleAtRiskRoute,
  ConsoleConsoleDashboardRoute: ConsoleConsoleDashboardRoute,
  ConsoleConsoleDriversRoute: ConsoleConsoleDriversRoute,
  ConsoleConsoleMerchantsRoute: ConsoleConsoleMerchantsRoute,
  ConsoleConsoleConsoleDeliveryCompaniesRoute:
    ConsoleConsoleConsoleDeliveryCompaniesRoute,
  ConsoleConsoleShipmentsShipmentIdRoute:
    ConsoleConsoleShipmentsShipmentIdRoute,
  ConsoleConsoleShipmentsNewRoute: ConsoleConsoleShipmentsNewRoute,
  ConsoleConsoleShipmentsIndexRoute: ConsoleConsoleShipmentsIndexRoute,
}

const ConsoleConsoleRouteWithChildren = ConsoleConsoleRoute._addFileChildren(
  ConsoleConsoleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  TrackRoute: TrackRoute,
  ConsoleConsoleRoute: ConsoleConsoleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
